# Generated by Django 2.2.4 on 2019-08-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190825_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='data',
        ),
        migrations.AddField(
            model_name='report',
            name='file_path',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
